USE railway;

-- =========================================================
-- DEMO DATA FOR EMPLOYEE CAB POOLING SYSTEM
-- =========================================================
-- Demo employee password for all accounts:
-- demo123
--
-- IMPORTANT:
-- Cabs and routes are intentionally NOT hard-coded here.
-- They should be generated by the application's pooling
-- and routing algorithms from the active bookings.
-- =========================================================


-- =========================================================
-- 1. OFFICES
-- =========================================================

INSERT INTO offices
(
    name,
    latitude,
    longitude,
    address
)
VALUES
(
    'Gurugram Tech Park',
    28.4595,
    77.0266,
    'Sector 44, Gurugram, Haryana'
),
(
    'Cyber City Office',
    28.4949,
    77.0895,
    'DLF Cyber City, Gurugram, Haryana'
);


-- =========================================================
-- 2. SHIFTS
-- =========================================================

INSERT INTO shifts
(
    office_id,
    shift_name,
    start_time,
    max_ride_minutes
)
VALUES
(
    1,
    'Morning Shift',
    '09:00:00',
    90
),
(
    1,
    'Evening Shift',
    '14:00:00',
    90
),
(
    2,
    'Night Shift',
    '23:00:00',
    90
);


-- =========================================================
-- 3. DEMO USERS
-- =========================================================

INSERT INTO users
(
    username,
    password_hash,
    role
)
VALUES

('demo01', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo02', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo03', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo04', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo05', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo06', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo07', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo08', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo09', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo10', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo11', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo12', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo13', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo14', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo15', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo16', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo17', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo18', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo19', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo20', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo21', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo22', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo23', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo24', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE'),
('demo25', 'pbkdf2:sha256:600000$a5329dcf65cecaf7$91307863486e085556bebdadbcd60c5cd6d8b88d955f4d7bc362f0f2ec7e30e1', 'EMPLOYEE');


-- =========================================================
-- 4. DEMO EMPLOYEES
-- =========================================================
-- Employees 1-10  -> Morning cluster
-- Employees 11-18 -> Evening cluster
-- Employees 19-25 -> Night cluster
-- =========================================================

INSERT INTO employees
(
    user_id,
    name,
    phone,
    gender,
    home_latitude,
    home_longitude
)
SELECT
    id,
    CASE username
        WHEN 'demo01' THEN 'Aman Sharma'
        WHEN 'demo02' THEN 'Rohit Kumar'
        WHEN 'demo03' THEN 'Priya Singh'
        WHEN 'demo04' THEN 'Yash Verma'
        WHEN 'demo05' THEN 'Neha Gupta'
        WHEN 'demo06' THEN 'Arjun Mehta'
        WHEN 'demo07' THEN 'Simran Kaur'
        WHEN 'demo08' THEN 'Karan Malhotra'
        WHEN 'demo09' THEN 'Ananya Rao'
        WHEN 'demo10' THEN 'Vivek Jain'
        WHEN 'demo11' THEN 'Rahul Sharma'
        WHEN 'demo12' THEN 'Pooja Mehta'
        WHEN 'demo13' THEN 'Aditya Kapoor'
        WHEN 'demo14' THEN 'Sneha Verma'
        WHEN 'demo15' THEN 'Mohit Bansal'
        WHEN 'demo16' THEN 'Riya Agarwal'
        WHEN 'demo17' THEN 'Nikhil Saini'
        WHEN 'demo18' THEN 'Kavya Singh'
        WHEN 'demo19' THEN 'Raj Malhotra'
        WHEN 'demo20' THEN 'Meera Joshi'
        WHEN 'demo21' THEN 'Vikram Rao'
        WHEN 'demo22' THEN 'Ishita Gupta'
        WHEN 'demo23' THEN 'Sahil Arora'
        WHEN 'demo24' THEN 'Tanya Kapoor'
        WHEN 'demo25' THEN 'Manish Yadav'
    END,

    CONCAT(
        '98',
        LPAD(id, 8, '0')
    ),

    CASE
        WHEN username IN
        (
            'demo03',
            'demo05',
            'demo07',
            'demo09',
            'demo12',
            'demo14',
            'demo16',
            'demo18',
            'demo20',
            'demo22',
            'demo24'
        )
        THEN 'Female'

        ELSE 'Male'
    END,

    CASE username

        WHEN 'demo01' THEN 28.4630
        WHEN 'demo02' THEN 28.4642
        WHEN 'demo03' THEN 28.4618
        WHEN 'demo04' THEN 28.4651
        WHEN 'demo05' THEN 28.4598
        WHEN 'demo06' THEN 28.4625
        WHEN 'demo07' THEN 28.4579
        WHEN 'demo08' THEN 28.4660
        WHEN 'demo09' THEN 28.4607
        WHEN 'demo10' THEN 28.4588

        WHEN 'demo11' THEN 28.4370
        WHEN 'demo12' THEN 28.4392
        WHEN 'demo13' THEN 28.4358
        WHEN 'demo14' THEN 28.4410
        WHEN 'demo15' THEN 28.4385
        WHEN 'demo16' THEN 28.4420
        WHEN 'demo17' THEN 28.4365
        WHEN 'demo18' THEN 28.4401

        WHEN 'demo19' THEN 28.4930
        WHEN 'demo20' THEN 28.4960
        WHEN 'demo21' THEN 28.4915
        WHEN 'demo22' THEN 28.4980
        WHEN 'demo23' THEN 28.4945
        WHEN 'demo24' THEN 28.4898
        WHEN 'demo25' THEN 28.4970

    END,

    CASE username

        WHEN 'demo01' THEN 77.0220
        WHEN 'demo02' THEN 77.0255
        WHEN 'demo03' THEN 77.0290
        WHEN 'demo04' THEN 77.0200
        WHEN 'demo05' THEN 77.0270
        WHEN 'demo06' THEN 77.0320
        WHEN 'demo07' THEN 77.0180
        WHEN 'demo08' THEN 77.0300
        WHEN 'demo09' THEN 77.0240
        WHEN 'demo10' THEN 77.0340

        WHEN 'demo11' THEN 77.0520
        WHEN 'demo12' THEN 77.0550
        WHEN 'demo13' THEN 77.0490
        WHEN 'demo14' THEN 77.0580
        WHEN 'demo15' THEN 77.0535
        WHEN 'demo16' THEN 77.0470
        WHEN 'demo17' THEN 77.0600
        WHEN 'demo18' THEN 77.0500

        WHEN 'demo19' THEN 77.0870
        WHEN 'demo20' THEN 77.0910
        WHEN 'demo21' THEN 77.0850
        WHEN 'demo22' THEN 77.0940
        WHEN 'demo23' THEN 77.0890
        WHEN 'demo24' THEN 77.0830
        WHEN 'demo25' THEN 77.0960

    END

FROM users
WHERE username LIKE 'demo%';


-- =========================================================
-- 5. BOOKINGS
-- =========================================================
-- Demo date: 25 September 2026
--
-- Morning: employees 1-10
-- Evening: employees 11-14
-- Night: employees 19-22
--
-- Employees 15-18 and 23-25 remain unbooked.
-- They can be used for demonstrating late bookings.
-- =========================================================

INSERT INTO bookings
(
    employee_id,
    shift_id,
    booking_date,
    status
)
SELECT
    e.id,
    1,
    '2026-09-25',
    'ACTIVE'
FROM employees e
JOIN users u
    ON e.user_id = u.id
WHERE u.username IN
(
    'demo01',
    'demo02',
    'demo03',
    'demo04',
    'demo05',
    'demo06',
    'demo07',
    'demo08',
    'demo09',
    'demo10'
);


INSERT INTO bookings
(
    employee_id,
    shift_id,
    booking_date,
    status
)
SELECT
    e.id,
    2,
    '2026-09-25',
    'ACTIVE'
FROM employees e
JOIN users u
    ON e.user_id = u.id
WHERE u.username IN
(
    'demo11',
    'demo12',
    'demo13',
    'demo14'
);


INSERT INTO bookings
(
    employee_id,
    shift_id,
    booking_date,
    status
)
SELECT
    e.id,
    3,
    '2026-09-25',
    'ACTIVE'
FROM employees e
JOIN users u
    ON e.user_id = u.id
WHERE u.username IN
(
    'demo19',
    'demo20',
    'demo21',
    'demo22'
);


-- =========================================================
-- 6. ONE CANCELLED BOOKING
-- =========================================================
-- This provides cancellation history without affecting
-- the main active pool.
-- =========================================================

INSERT INTO bookings
(
    employee_id,
    shift_id,
    booking_date,
    status
)
SELECT
    e.id,
    1,
    '2026-09-25',
    'CANCELLED'
FROM employees e
JOIN users u
    ON e.user_id = u.id
WHERE u.username = 'demo15';


-- =========================================================
-- DEMO DATA SUMMARY
-- =========================================================
--
-- Users:       25
-- Employees:   25
-- Offices:      2
-- Shifts:       3
-- Active bookings:
--   Morning:   10
--   Evening:    4
--   Night:      4
-- Total:       18
--
-- Cancelled bookings: 1
--
-- Unbooked employees:
--   demo15, demo16, demo17, demo18,
--   demo23, demo24, demo25
--
-- These can be used for late-booking demonstrations.
--
-- IMPORTANT:
-- Generate active cabs through the application.
-- Do NOT manually insert cabs here.
-- =========================================================